# Generated by Django 3.2.7 on 2021-09-25 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CrollData',
        ),
    ]
