# Generated by Django 3.2.7 on 2021-09-25 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_alter_review_writer'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrollData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('link', models.CharField(max_length=500)),
            ],
        ),
    ]
